### ISSUE TITLE
Ruby 2.2 compatibility

### ISSUE THREAD

**Issue by voxik** [jkraemer/ferret#12]
I can't build ferret against Ruby 2.2:

~~~
r_analysis.c: In function 'frb_rb_hash_size':
r_analysis.c:68:5: warning: implicit declaration of function 'RHASH' [-Wimplicit-function-declaration]
     return RHASH(hash)->ntbl->num_entries;
     ^
r_analysis.c:68:23: error: invalid type argument of '->' (have 'int')
     return RHASH(hash)->ntbl->num_entries;
                       ^
r_analysis.c:72:1: warning: control reaches end of non-void function [-Wreturn-type]
 }
 ^
Makefile:238: recipe for target 'r_analysis.o' failed
make: *** [r_analysis.o] Error 1
~~~

**Comment by quasarj** [comment]
I was having this same problem (needing ferret for vorax4). It looks like changing that line (r_analysis.c:68) to: 
  RHASH_SIZE(hash);

Should fix the problem.

**Comment by jkraemer** [comment]
Would you mind doing a proper pull request for that?

**Comment by voxik** [comment]
This is patch authored by @mtasaka used in Fedora if that is sufficient:

http://pkgs.fedoraproject.org/cgit/rubygem-ferret.git/tree/rubygem-ferret-0.11.8.4-ruby22-hashsize.patch

**Comment by jkraemer** [comment]
I applied the patch and pushed a new gem (0.11.8.6).
